version: '3.9'
name: dormbookings
services:
  web:
    container_name: web_dorm
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./web/Dockerfile
    ports:
      - "80:80"
    volumes:
      - web_data:/var/www/html
      - ./src:/var/www/html
      - ./default.conf/default.conf:/etc/nginx/conf.d/default.conf
      - ./default.conf/nginx.conf:/etc/nginx/nginx.conf
    networks:
      nursing_network:
        ipv4_address: 192.168.30.2

  php:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./php/Dockerfile
    volumes:
      - ./src:/var/www/html
    networks:
      nursing_network:
        ipv4_address: 192.168.30.3

  phpmyadmin:
    restart: unless-stopped
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_dorm
    environment:
      PMA_HOST: mysql
    depends_on:
      - mysql
    ports:
      - "81:80"
    networks:
      nursing_network:
        ipv4_address: 192.168.30.4

  mysql:
    restart: unless-stopped
    image: mysql:latest
    container_name: mysqldorm
    environment:
      MYSQL_ROOT_PASSWORD: adminkku
      MYSQL_DATABASE: dormtest
      MYSQL_USER: kku
      MYSQL_PASSWORD: kku
    networks:
      nursing_network:
        ipv4_address: 192.168.30.5

    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --default-authentication-plugin=caching_sha2_password


networks:
  nursing_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.30.0/24

volumes:
  web_data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/srv/docker_data/web'  # เปลี่ยนเป็นที่อยู่ของโฟลเดอร์บนเครื่องโฮสต์ที่คุณต้องการเชื่อมต่อกับ container